## Definicion de la URL para el trackingmlflow.set_tracking_uri(uri="http://127.0.0.1:8080") ## Creación del nuevo experimento con MLflowmlflow.set_experiment("MLflow Quickstart")
name: CD - Promoción y Despliegue de Modelo
on:
  workflow_dispatch:
jobs:
  deploy-model:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt
      - name: Descargar artefactos del run anterior
        uses: actions/download-artifact@v4
        with:
          name: mlruns
          path: mlruns/
      - name: Promocionar modelo (simulado)
        run: |
          echo "✅ Promoción del modelo validado a producción"
          # Aquí puedes agregar comandos para actualizar el estado del modelo en MLflow Registry
          # o desplegarlo usando mlflow models serve