# .github/workflows/ci.yml
name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - run: make install
      - run: make format-check   # o 'make format' si quieres autoformatear
      - run: make train
      - run: make evaluate

      - uses: actions/upload-artifact@v4
        with:
          name: mlruns
          path: mlruns